### ISSUE TITLE
Downloads never start after switching to AIFF format

### ISSUE THREAD

**Issue by adidahiya** [hyphmongo/batchcamp#1]
v1.0.0 from releases page

![2022-07-29 10 25 49](https://user-images.githubusercontent.com/723999/181781438-99764a1b-c563-4494-91b6-794ce18a61c8.gif)

I got this error in the console:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/723999/181781707-4ca4a40c-3f06-4929-adf7-15dc3df4edae.png">

**Comment by hyphmongo** [comment]
Thanks! Fixed and pushed a new release https://github.com/hyphmongo/batchcamp/releases/tag/v1.0.1
