### ISSUE TITLE
Downloads window open but doesn't charge any files to download / using Firefox 115.5.0esr (64-bit)

### ISSUE THREAD

**Issue by allotonio** [hyphmongo/batchcamp#10]
Hello, i have an issue with the add-on using latest version of Firefox - 115.5.0esr (64-bit). 
When checking an album to download, the downloads window open correctly but doesn't charge the files to download / nothing happens. ... can you help me ?

**Comment by hyphmongo** [comment]
Thanks for the report!

This was an issue with the `autoDiscardable` property which is set on tabs to keep them alive and stop them being cleaned up by the browser. Support for this was only added in Firefox 116 so was erroring when trying to update in 115

Have updated and published a new version 1.2.2 which will check if this property is available before trying to update.

This may have a side-effect of your tab being cleaned up by the browser if left open for too long. If you run into this issue please let me know. You could also try setting `browser.tabs.unloadOnLowMemory` to false in `about:config`

**Comment by allotonio** [comment]
it works fine now ... thanks for your help
