### ISSUE TITLE
Unable to change format to download song files

### ISSUE THREAD

**Issue by nPrevail** [hyphmongo/batchcamp#11]
Perhaps I'm missing it, but it's documented that Batchcamp can change format from these directions: 
_Clicking the extension icon will popup the options screen where you can set the default download format and the number of downloads to process at once._

I haven't been able to find that popup option screen to change the default format and number of downloads to process.

Could you share any details to where I can find such selection? I'd prefer to download my files in FLAC.

![Screen Shot 2023-11-27 at 1 05 57 PM](https://github.com/hyphmongo/batchcamp/assets/57690587/43fa3f57-1491-4942-a064-50b8e9d84634)

![Screen Shot 2023-11-27 at 1 06 19 PM](https://github.com/hyphmongo/batchcamp/assets/57690587/03366199-ea54-4915-bfe1-06f29ad7a670)

**Comment by nPrevail** [comment]
I probably should have did more research. This link best explains how to change format:

https://howtohifi.com/bulk-download-your-entire-bandcamp-collection-with-batchcamp-chrome-extension/

**Comment by hyphmongo** [comment]
Thanks for raising this! 

I've had a few people ask how to change format and some people not realize it was possible. I think this means I'm not pointing it out well enough.

Will update the docs to try signpost this a bit better and see if there are other ways to access these settings that are more obvious.
