### ISSUE TITLE
When I click on the extension button nothing happens

### ISSUE THREAD

**Issue by Nicos18** [hyphmongo/batchcamp#14]
When I click on the extension button nothing happens; also, I tried to select some albums to download, but the download doesn't start.

I tried both Edge and Chrome with no success.

**Comment by hyphmongo** [comment]
in the latest version i moved the options out of the extension button and in to the main tab to make it more noticable for people

i couldn't see any errors in my error tracking tool, did you manage to get everything working?

**Comment by Nicos18** [comment]
Yes,

I don't know what happened, but the next day it worked correctly.

Thanks.
