### ISSUE TITLE
Select all not working when filter is applied

### ISSUE THREAD

**Issue by mainrs** [hyphmongo/batchcamp#15]
For example if I want to download everything by "Artist A". I enter their name inside the filter collection search field. But when clicking on the select all button, the button loads for quite a long time (~10s). Then, the button's text becomes "select all" again.

I'd expect the button to select everything that is visible on the page.

**Comment by GOTO-GOSUB** [comment]
+1 for this, I have the same issue.

**Comment by hyphmongo** [comment]
Thanks for the report :)

I've double checked and it seems like there is no pagination on the filter results so I've added a quick fix that will select all items viewable in the filtered list after a short waiting period.

New version 1.4.5 is rolling out on chrome and firefox extension stores.

Please let me know if this fixes the issue.
