### ISSUE TITLE
Select All Button overlaps Now Playing toggle button

### ISSUE THREAD

**Issue by batrinu** [hyphmongo/batchcamp#17]
Hello good sir, your extension is a godsend, after some recent changes with the bandcamp ui I noticed the Select All button overlaps the Now Playing icon, I seem to easily resolve this from the devl tools by changing the class of the button from w-32 to w-16
![screenshot-bandcamp_com-2024_08_11-11_48_57](https://github.com/user-attachments/assets/4a906a8a-ea15-470b-b651-44e1cc88a9e4)

**Comment by hyphmongo** [comment]
Thank you for the report :)

This has been fixed and rolling out in 1.4.7
