### ISSUE TITLE
Feature Request - Select All Button

### ISSUE THREAD

**Issue by RossMurr4y** [hyphmongo/batchcamp#8]
# Description of Feature

An option to 'select all' from my collection page, rather than individually select each item for download.

# Context

With the recent sale of Bandcamp (yet again) people are understandably looking to back up their entire collections. 

Batchcamp is the go-to tool for this, yet even with my rather modest collection, the individual selection is quite effortful. If feasible, this quality-of-life feature would go a long way.

**Comment by gml3ff** [comment]
Hey @RossMurr4y. I was wondering how to do this myself and am currently backing things up as we speak. It is actually possible today if you do the following: 

1. Navigate to your "Collection" page. 
2. Select the first item in your collection (first release in the top left corner). 
3. Hold down the "Shift" key
4. Scroll to the bottom of the page, then select the last item (last release in bottom right corner). 
5. Click "Download x Items"

This should allow you to download everything, although it would be nice to have this more directly integrated into the plugin.

**Comment by hyphmongo** [comment]
Thanks for submitting this :) 

Have been thinking about this feature previously when someone reported having over 20k items in their collection, scrolling for that long to load it all would kinda suck! A few people also haven't been aware of the multi-select functionality so having a single "Select all" button would be super helpful

I still need to figure out how the UI would work overall and if there is a non-janky way to takeover the automatic scrolling to go through all the infinitely loaded list but it's something I want to tackle next

**Comment by RossMurr4y** [comment]
Legend, thank you very much!
