### ISSUE TITLE
Firefox: does not play nice with containers

### ISSUE THREAD

**Issue by FelipeLema** [hyphmongo/batchcamp#9]
say I have the site opened in a "b" container, but not logged in in any other container

clicking the "download N items" button will open in the default container and the download will fail because I'm not logged in in that container. normally clicking a link that opens a new tab will open it in the same container

Maybe important: I'm using [conex](https://addons.mozilla.org/en-US/firefox/addon/conex/)

**Comment by hyphmongo** [comment]
Thanks for submitting an issue! 

Now passing along the current `cookieStoreId` to the new tab which should associate it with the container. Have tested with the Multi-Account Containers extension and seems to be good

Published as a new version v1.1.3, please close the issue if that fixes it for you : - )

**Comment by FelipeLema** [comment]
running late, but came here to confirm that it's fixed now

thanks
